kind: Deployment
apiVersion: apps/v1
metadata:
  name: incptserver-dpl
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: incptserver
    spec:
      containers:
        - name: server
          image: registry.cn-zhangjiakou.aliyuncs.com/huangyz/inceptionserver:1.0
          ports:
           - containerPort: 8003
  

